platform: "tensorrt_plan"
max_batch_size: 128
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [3, 640, 640]
  }
]
output [
  {
    name: "boxes"
    data_type: TYPE_FP32
    dims: [-1, -1]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [-1, 1]
  },
  {
    name: "classes"
    data_type: TYPE_FP32
    dims: [-1, 1]
  }
]
instance_group {
  kind: KIND_GPU
  count: 1
  gpus: 0
}
version_policy: { specific: { versions: [3]}}