version: '3.8'
services:
  service_manager:
    image: service_manager:latest
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock