version: '3.8'

services:
  tarsier_video:
    container_name: tarsier-video
    build: .
    ports:
      - "9090:9090"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/app              
    networks:
      - kairos
      
networks:
  kairos:
    driver: bridge